const {onCall,HttpsError}=require('firebase-functions/v2/https');
const admin=require('firebase-admin');admin.initializeApp();const db=admin.firestore();
const TEST='math-live-01',DURATION=45*60*1000;
function isAdmin(req){return !!req.auth&&req.auth.token&&req.auth.token.admin===true}
exports.startSession=onCall({region:'asia-south1'},async req=>{if(!req.auth)throw new HttpsError('unauthenticated','Sign-in required');const name=String(req.data?.candidateName||'').trim().slice(0,60);if(!name)throw new HttpsError('invalid-argument','Candidate name required');const snap=await db.collection('questions').where('testId','==',TEST).orderBy('number').get();if(snap.size!==50)throw new HttpsError('failed-precondition','Test must contain 50 questions');const sid=db.collection('sessions').doc(),started=Date.now();await sid.set({uid:req.auth.uid,testId:TEST,candidateName:name,startedAt:started,status:'active'});return{sessionId:sid.id,startedAt:started,questions:snap.docs.map(d=>{const x=d.data();return{id:d.id,number:x.number,topic:x.topic,text:x.text,options:x.options}})};});
exports.submitSession=onCall({region:'asia-south1'},async req=>{if(!req.auth)throw new HttpsError('unauthenticated','Sign-in required');const answers=Array.isArray(req.data?.answers)?req.data.answers:[];const active=await db.collection('sessions').where('uid','==',req.auth.uid).where('testId','==',TEST).where('status','==','active').orderBy('startedAt','desc').limit(1).get();if(active.empty)throw new HttpsError('failed-precondition','No active test session');const session=active.docs[0],s=session.data(),elapsed=Math.max(0,Date.now()-s.startedAt);const effective=elapsed>DURATION+15000?Array(50).fill(null):answers;const qs=await db.collection('questions').where('testId','==',TEST).orderBy('number').get();const keys=await db.collection('answerKeys').where('testId','==',TEST).orderBy('number').get();if(qs.size!==50||keys.size!==50)throw new HttpsError('failed-precondition','Test data incomplete');let correct=0,wrong=0,review=[];for(let i=0;i<50;i++){const q=qs.docs[i].data(),k=keys.docs[i].data(),a=effective[i]??null,is=a!==null&&a===k.answer;if(a!==null){if(is)correct++;else wrong++}review.push({question:q.text,selected:a===null?null:q.options[a],correct:q.options[k.answer],isCorrect:is,explanation:k.explanation})}const unattempted=50-correct-wrong,score=Number((correct-wrong*.25).toFixed(2)),percentage=score*2,timeUsed=fmt(Math.min(elapsed,DURATION)),result={candidateName:s.candidateName,score,percentage,correct,wrong,unattempted,timeUsed,testId:TEST,submittedAt:admin.firestore.FieldValue.serverTimestamp()};await db.collection('results').add({...result,uid:req.auth.uid});await db.collection('publicResults').add(result);await session.ref.update({status:'submitted',submittedAt:admin.firestore.FieldValue.serverTimestamp()});return{...result,review};});
exports.adminGetResults=onCall({region:'asia-south1'},async req=>{if(!isAdmin(req))throw new HttpsError('permission-denied','Admin only');const snap=await db.collection('results').where('testId','==',TEST).orderBy('score','desc').limit(500).get();return{results:snap.docs.map(d=>({id:d.id,...d.data()}))}});
exports.adminResetResults=onCall({region:'asia-south1'},async req=>{if(!isAdmin(req))throw new HttpsError('permission-denied','Admin only');const snap=await db.collection('results').where('testId','==',TEST).get();const pub=await db.collection('publicResults').where('testId','==',TEST).get();let batch=db.batch(),n=0;for(const d of [...snap.docs,...pub.docs]){batch.delete(d.ref);if(++n===450){await batch.commit();batch=db.batch();n=0}}if(n)await batch.commit();return{deleted:snap.size+pub.size}});
exports.adminDeleteResult=onCall({region:'asia-south1'},async req=>{if(!isAdmin(req))throw new HttpsError('permission-denied','Admin only');const id=String(req.data?.id||'');if(!id)throw new HttpsError('invalid-argument','Result id required');await db.collection('results').doc(id).delete();return{deleted:id}});
function fmt(ms){let s=Math.floor(ms/1000),m=Math.floor(s/60);s%=60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
